### ISSUE TITLE
Get official LoL assets (images, ...) and understand regulations

### ISSUE THREAD

**Issue by cyrlop** [kevinrue/lolgenie#17]
- [ ] Figure out the best way to get official LoL assets
    - Clone an official repo as sub-module?
    - Find a "fan-made" repository?
    - Manually gather everything?
- [ ] Agree on a practice to regularly update (patches, etc...)
    - This step is easier if we use a third-party repository
- [ ] Understand if we can freely use these images, if Riot needs to agree or something else
- [ ] Actually get the assets

**Comment by kevinrue** [comment]
In addition to #20, I guess this answers our concerns:
![image](https://user-images.githubusercontent.com/5769108/104359288-5f7b9a00-5507-11eb-88d7-57b4f5f602f3.png)
