### ISSUE TITLE
Widen a bit the text box for summoner name

### ISSUE THREAD

**Issue by kevinrue** [kevinrue/lolgenie#21]
![image](https://user-images.githubusercontent.com/5769108/104358772-d1071880-5506-11eb-9254-81bdff036331.png)

Just so that it fits the entire "Summoner name".

**Comment by cyrlop** [comment]
Bizarre chez moi c'est pile poil
![image](https://user-images.githubusercontent.com/15691907/104387883-548d2d80-5538-11eb-9822-04afe79ab809.png)
Ca doit dépendre de la résolution, de la police etc... Je règlerais ça ^^
